//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swatiSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antiguedad_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Antiguedad_Empleado()
        {
            this.Empleadoes = new HashSet<Empleado>();
        }
    
        public System.Guid Id { get; set; }
        public string Concepto { get; set; }
        public int Limite_Antiguedad { get; set; }
        public double Porcentage { get; set; }
        public System.DateTime CreadoEn { get; set; }
        public Nullable<System.DateTime> ActualizadoEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleadoes { get; set; }
    }
}
