//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swatiSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Horas_Extras_Empleado = new HashSet<Horas_Extras_Empleado>();
            this.Seguridad_Social_Empleado = new HashSet<Seguridad_Social_Empleado>();
            this.Solicitud_Vacaciones_Empleado = new HashSet<Solicitud_Vacaciones_Empleado>();
        }
    
        public System.Guid Id { get; set; }
        public string Codigo_Empleado { get; set; }
        public string Cedula_Identidad { get; set; }
        public string Codigo_Inss { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public decimal Salario_Bruto { get; set; }
        public int Vacaciones_Acumulados { get; set; }
        public System.Guid Cargo_Empleado_Id { get; set; }
        public Nullable<System.Guid> Antiguedad_Empleado_Id { get; set; }
        public System.DateTime CreadoEn { get; set; }
        public Nullable<System.DateTime> ActualizadoEn { get; set; }
    
        public virtual Antiguedad_Empleado Antiguedad_Empleado { get; set; }
        public virtual Cargo_Empleado Cargo_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horas_Extras_Empleado> Horas_Extras_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguridad_Social_Empleado> Seguridad_Social_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Vacaciones_Empleado> Solicitud_Vacaciones_Empleado { get; set; }
    }
}
