//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swatiSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class swatiEntities : DbContext
    {
        public swatiEntities()
            : base("name=swatiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Antiguedad_Empleado> Antiguedad_Empleado { get; set; }
        public virtual DbSet<Cargo_Empleado> Cargo_Empleado { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Horas_Extras_Empleado> Horas_Extras_Empleado { get; set; }
        public virtual DbSet<Seguridad_Social_Empleado> Seguridad_Social_Empleado { get; set; }
        public virtual DbSet<Solicitud_Vacaciones_Empleado> Solicitud_Vacaciones_Empleado { get; set; }
    }
}
