//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swatiSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad_Social_Empleado
    {
        public System.Guid Id { get; set; }
        public decimal Deduccion_Base { get; set; }
        public decimal Deduccion_IR { get; set; }
        public decimal Pago_Patronal { get; set; }
        public System.DateTime Fecha_Aplicacion_Impuesto { get; set; }
        public System.Guid Empleado_Id { get; set; }
        public System.DateTime CreadoEn { get; set; }
        public Nullable<System.DateTime> ActualizadoEn { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
