//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swatiSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Vacaciones_Empleado
    {
        public System.Guid Id { get; set; }
        public int Dias_De_Vacaciones { get; set; }
        public decimal Vacaciones_Pagadas { get; set; }
        public System.DateTime Fecha_Aplicacion { get; set; }
        public System.Guid Empleado_Id { get; set; }
        public System.DateTime CreadoEn { get; set; }
        public Nullable<System.DateTime> ActualizadoEn { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
